#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require 'prism'
rescue LoadError
  abort 'Prism is required to build the bundle; install Ruby 3.3 or newer.'
end

require 'date'
require 'fileutils'

module LogBuilderBundler # rubocop:disable Metrics/ModuleLength
  SOURCE_ORDER = %w[
    src/constants/app_constants.rb
    src/constants/config_constants.rb
    src/models/day.rb
    src/models/year.rb
    src/services/config_reader_service.rb
    src/services/task_printer_service.rb
    src/services/tag_merge_service.rb
    src/services/add_task_service.rb
    src/services/printer_service.rb
    src/services/configured_tasks_service.rb
    src/services/input_validation_service.rb
    src/modules/log_builder.rb
    src/run.rb
  ].freeze

  BUILD_DIR = 'builds'
  FILE_PREFIX = 'log-builder_'
  DATE_FORMAT = '%Y-%m-%d'

  HEADER = <<~HEADER
    #!/usr/bin/env ruby
    # Generated by build.rb from src/. Do not edit by hand.
    # Run `ruby build.rb` to regenerate.
    require 'yaml'
    require 'fileutils'
  HEADER

  HEADER_REQUIRES = %w[yaml fileutils].freeze

  LITERAL_NODE_TYPES = [
    Prism::StringNode,
    Prism::InterpolatedStringNode,
    Prism::XStringNode,
    Prism::InterpolatedXStringNode,
    Prism::SymbolNode,
    Prism::InterpolatedSymbolNode,
    Prism::RegularExpressionNode,
    Prism::InterpolatedRegularExpressionNode,
    Prism::MatchLastLineNode
  ].freeze

  module_function

  def build(root)
    requires = []
    bodies = SOURCE_ORDER.map do |source|
      body, names = strip_source(File.read(File.join(root, source), encoding: 'UTF-8'))
      names.each { |name| requires << name unless requires.include?(name) }
      "# #{source}\n#{body}"
    end

    message = "Recorded requires #{requires.inspect} do not match HEADER_REQUIRES #{HEADER_REQUIRES.inspect}; " \
              'update HEADER and HEADER_REQUIRES together.'
    raise message unless requires == HEADER_REQUIRES

    "#{([HEADER.chomp] + bodies).join("\n\n")}\n"
  end

  def write(root, date:)
    bundle = build(root)
    directory = File.join(root, BUILD_DIR)
    FileUtils.mkdir_p(directory)
    path = File.join(directory, "#{FILE_PREFIX}#{date.strftime(DATE_FORMAT)}")
    File.binwrite(path, bundle)
    File.chmod(0o755, path)
    path
  end

  def strip_source(text)
    requires = []
    remaining = text.each_line.reject do |line|
      name = non_relative_require_name(line)
      requires << name if name
      require_line?(line)
    end.join
    parsed = Prism.parse(remaining)
    comment_ranges = parsed.comments.map(&:location)
    literal_ranges = []
    collect_literal_ranges(parsed.value, literal_ranges)

    lines = []
    offset = 0
    remaining.each_line do |line|
      line_start = offset
      offset += line.length

      if inside_range?(literal_ranges, line_start)
        lines << line.chomp
        next
      end

      stripped = strip_comments(line, line_start, comment_ranges).sub(/\A[ \t]+/, '').chomp
      lines << stripped unless stripped.strip.empty?
    end

    [lines.join("\n"), requires]
  end

  def require_line?(line)
    stripped = line.strip
    stripped.match?(/\Arequire_relative\b/) || stripped.match?(/\Arequire\s+['"][^'"]+['"]/)
  end

  def non_relative_require_name(line)
    match = line.strip.match(/\Arequire\s+['"]([^'"]+)['"]/)
    return nil if match.nil?

    name = match[1]
    name.start_with?('.', '/') ? nil : name
  end

  def collect_literal_ranges(node, ranges)
    return if node.nil?

    if LITERAL_NODE_TYPES.any? { |type| node.is_a?(type) }
      ranges << node.location
      ranges << node.content_loc if node.respond_to?(:heredoc?) && node.heredoc?
    end

    node.child_nodes.each { |child| collect_literal_ranges(child, ranges) }
  end

  def inside_range?(ranges, offset)
    ranges.any? { |range| range.start_offset < offset && offset < range.end_offset }
  end

  def strip_comments(line, line_start, comment_ranges)
    line_end = line_start + line.length
    content = line.dup
    intersecting = comment_ranges.select { |range| range.start_offset < line_end && range.end_offset > line_start }
    intersecting.sort_by { |range| -range.start_offset }.each do |range|
      from = [range.start_offset - line_start, 0].max
      to = [range.end_offset - line_start, content.length].min
      content.slice!(from, to - from) if to > from
    end
    content
  end
end

LogBuilderBundler.write(File.expand_path(__dir__), date: Date.today) if __FILE__ == $PROGRAM_NAME
