# frozen_string_literal: true

require './build'
require './src/constants/app_constants'
require 'open3'
require 'tmpdir'
require 'fileutils'
require 'date'

ROOT = File.expand_path('../..', __dir__)

describe 'LogBuilderBundler' do
  subject(:bundle) { LogBuilderBundler.build(ROOT) }

  def compare_outputs(config, mode, year, month, file)
    Dir.mktmpdir do |dir|
      bundle_path = File.join(dir, 'bundle.rb')
      File.binwrite(bundle_path, bundle)
      src_out = File.join(dir, 'src_out')
      bundle_out = File.join(dir, 'bundle_out')

      _src_stdout, _src_stderr, src_status =
        Open3.capture3('ruby', './src/run.rb', config, mode, year, month, src_out, chdir: ROOT)
      _bundle_stdout, _bundle_stderr, bundle_status =
        Open3.capture3('ruby', bundle_path, config, mode, year, month, bundle_out, chdir: ROOT)

      expect(src_status.exitstatus).to eq(0)
      expect(bundle_status.exitstatus).to eq(0)
      expect(File.binread(File.join(bundle_out, file))).to eq(File.binread(File.join(src_out, file)))
    end
  end

  it 'starts with the ruby shebang' do
    expect(bundle.lines.first.chomp).to eq('#!/usr/bin/env ruby')
  end

  it 'names the generator on the second line' do
    expect(bundle.lines[1].chomp).to eq('# Generated by build.rb from src/. Do not edit by hand.')
  end

  it 'returns a String' do
    expect(bundle).to be_a(String)
  end

  it 'hoists the standard library requires before the first class or module' do
    expect(bundle.scan("require 'yaml'").length).to eq(1)
    expect(bundle.scan("require 'fileutils'").length).to eq(1)

    first_definition = bundle.lines.index { |line| line.match?(/\A(module|class)\b/) }
    yaml_index = bundle.lines.index { |line| line.include?("require 'yaml'") }
    fileutils_index = bundle.lines.index { |line| line.include?("require 'fileutils'") }

    expect(yaml_index).to be < first_definition
    expect(fileutils_index).to be < first_definition
  end

  it 'leaves no project requires' do
    expect(bundle).to_not match(/require_relative/)
    expect(bundle).to_not match(%r{require\s+['"]\./})
  end

  it 'labels each source section for backtrace mapping' do
    LogBuilderBundler::SOURCE_ORDER.each do |source|
      expect(bundle).to include("# #{source}\n")
    end
  end

  it 'is deterministic across calls' do
    expect(LogBuilderBundler.build(ROOT)).to eq(bundle)
  end

  it 'produces syntactically valid Ruby' do
    Dir.mktmpdir do |dir|
      path = File.join(dir, 'bundle.rb')
      File.binwrite(path, bundle)
      stdout, _stderr, status = Open3.capture3('ruby', '-c', path)

      expect(status.exitstatus).to eq(0)
      expect(stdout).to include('Syntax OK')
    end
  end

  it 'writes the bundle to a dated path with mode 0755 and overwrites' do
    Dir.mktmpdir do |dir|
      FileUtils.cp_r(File.join(ROOT, 'src'), dir)
      path = LogBuilderBundler.write(dir, date: Date.new(2026, 1, 1))

      expect(path).to eq(File.join(dir, 'builds', 'log-builder_2026-01-01'))
      expect(File.binread(path)).to eq(bundle)
      expect(File.stat(path).mode & 0o777).to eq(0o755)

      LogBuilderBundler.write(dir, date: Date.new(2026, 1, 1))
      expect(File.binread(path)).to eq(bundle)
    end
  end

  it 'matches the newest committed build snapshot' do
    tracked_stdout, _tracked_stderr, tracked_status =
      Open3.capture3('git', 'ls-files', '--', 'builds/', chdir: ROOT)
    expect(tracked_status.exitstatus).to eq(0)
    tracked = tracked_stdout.lines.map(&:chomp).select { |path| File.basename(path).start_with?('log-builder_') }

    if tracked.empty?
      snapshots = Dir.glob(File.join(ROOT, 'builds', 'log-builder_*')).sort

      expect(snapshots).to_not be_empty, 'No build snapshot found under builds/; run `ruby build.rb`'
      expect(bundle).to eq(File.binread(snapshots.last))
    else
      newest = tracked.max
      committed, _show_stderr, show_status = Open3.capture3('git', 'show', "HEAD:#{newest}", chdir: ROOT)

      expect(show_status.exitstatus).to eq(0)
      expect(bundle).to eq(committed)
    end
  end

  it 'tracks build.rb and every build snapshot with the executable bit set' do
    stdout, _stderr, status = Open3.capture3('git', 'ls-files', '-s', '--', 'build.rb', 'builds/', chdir: ROOT)

    expect(status.exitstatus).to eq(0)
    entries = stdout.lines.map(&:split)
    expect(entries.map { |entry| entry[3] }).to include('build.rb')

    executable = entries.select do |_mode, _sha, _stage, path|
      path == 'build.rb' || (path || '').start_with?('builds/log-builder_')
    end
    executable.each do |mode, _sha, _stage, path|
      expect(mode).to eq('100755'), "#{path} is missing the executable bit"
    end
  end

  it 'matches src/run.rb for a DO year' do
    compare_outputs('./test/test_config.yml', 'DO', '2020', 'ALL', 'DO_2020.md')
  end

  it 'matches src/run.rb for an LG year' do
    compare_outputs('./test/test_config.yml', 'LG', '2020', 'ALL', 'LG_2020.md')
  end

  it 'matches src/run.rb for tag order and merge' do
    compare_outputs('./test/tag_order_config.yml', 'DO', '2020', 'ALL', 'DO_2020.md')
  end

  it 'exits non-zero with the invalid config message when the config is missing' do
    Dir.mktmpdir do |dir|
      bundle_path = File.join(dir, 'bundle.rb')
      File.binwrite(bundle_path, bundle)
      stdout, _stderr, status =
        Open3.capture3('ruby', bundle_path, './test/fake_config.yml', 'DO', '2020', '1', dir, chdir: ROOT)

      expect(status.exitstatus).to_not eq(0)
      expect(stdout).to include(AppConstants::ERROR_MESSAGES[:INVALID_CONFIG_FILE])
    end
  end
end
