tasks:
  Sample:
    FirstTask:
      - Because
      - Strategy
      - Result
  apartment_trash_out: "Apartment(Trash_Out,)"
days:
  monday: 
    - Sample
special:
  birthdays:
    johnny: "2000-01-01"
  new_years_day:
    tag: "[Holiday_NewYears_Day]"
    type: specific_date
    rule:
      month: 1
      day: 1
  presidents_day:
    tag: "[Holiday_PresidentsDay]"
    type: nth_xday_in_month
    rule:
      month: 2
      nth_day: 3
      day_name: "Monday"
  memorial_day:
    tag: "[Holiday_MemorialDay]"
    type: "last_xday_in_month"
    rule:
      month: 5
      day_name: "Monday"
  fathers_day:
    tag: "[Holiday_FathersDay]"
    type: "nth_xday_in_month"
    rule:
      month: 6
      nth_day: 3
      day_name: "Sunday"

