tasks:
  1_Dimentional:
    - Level_1
  1_Dimentional_Double:
    - Level_1a
    - Level_1b
  2_Dimentional:
    Level_1:
      - Level_2
  2_Dimentional_Mixed:
    Level_1a:
      Level_2a:
        - Level_3a
      Level_2b:
  3_Dimentional:
    Level_1:
      Level_2:
        - Level_3
  3_Dimentional_Leaf_Siblings:
    Level_1:
      Level_2:
        - Level_3
        - Level_3
  3_Dimentional_Internal_Siblings:
    Level_1:
      Level_2a:
        - Level_3
      Level_2b:
        - Level_3
days:
  Monday:
    - 1_Dimentional
  Tuesday:
    - 1_Dimentional
    - 1_Dimentional
  Wednesday:
    - 3_Dimentional
  Thursday:
    - 1_Dimentional
    - 3_Dimentional
  Friday:
    - 3_Dimentional
templates:
  Birthday:
    - Name({{NAME}})
    - Contact({{CONTACT}})
special:
  birthdays:
    template: Birthday
    johnny: "2000-01-01"
  new_years_day:
    tag: "[Holiday_NewYears_Day]"
    type: specific_date
    rule:
      month: 1
      day: 1
  presidents_day:
    tag: "[Holiday_PresidentsDay]"
    type: nth_xday_in_month
    rule:
      month: 2
      nth_day: 3
      day_name: "Monday"
  memorial_day:
    tag: "[Holiday_MemorialDay]"
    type: "last_xday_in_month"
    rule:
      month: 5
      day_name: "Monday"
  fathers_day:
    tag: "[Holiday_FathersDay]"
    type: "nth_xday_in_month"
    rule:
      month: 6
      nth_day: 3
      day_name: "Sunday"
